# ---------------------------------------------------------------------------------------------------------------------
# ALLOY HELM CHART VALUES
# ---------------------------------------------------------------------------------------------------------------------

alloy:
  configMap:
    content: |-
      logging {
          level  = "info"
          format = "json"
      }

      discovery.kubernetes "pod" {
          role = "pod"
      }

      discovery.kubernetes "services" {
          role = "service"
      }

      discovery.kubernetes "nodes" {
          role = "node"
      }

      discovery.relabel "pod_logs" {
        targets = discovery.kubernetes.pod.targets

        // Label creation - "namespace" field from "__meta_kubernetes_namespace"
        rule {
          source_labels = ["__meta_kubernetes_namespace"]
          action = "replace"
          target_label = "namespace"
        }

        // Label creation - "pod" field from "__meta_kubernetes_pod_name"
        rule {
          source_labels = ["__meta_kubernetes_pod_name"]
          action = "replace"
          target_label = "pod"
        }

        // Label creation - "container" field from "__meta_kubernetes_pod_container_name"
        rule {
          source_labels = ["__meta_kubernetes_pod_container_name"]
          action = "replace"
          target_label = "container"
        }

        // Label creation -  "app" field from "__meta_kubernetes_pod_label_app_kubernetes_io_name"
        rule {
          source_labels = ["__meta_kubernetes_pod_label_app_kubernetes_io_name"]
          action = "replace"
          target_label = "app"
        }

        // Label creation -  "job" field from "__meta_kubernetes_namespace" and "__meta_kubernetes_pod_container_name"
        // Concatenate values __meta_kubernetes_namespace/__meta_kubernetes_pod_container_name
        rule {
          source_labels = ["__meta_kubernetes_namespace", "__meta_kubernetes_pod_container_name"]
          action = "replace"
          target_label = "job"
          separator = "/"
          replacement = "$1"
        }

        // Label creation - "container" field from "__meta_kubernetes_pod_uid" and "__meta_kubernetes_pod_container_name"
        // Concatenate values __meta_kubernetes_pod_uid/__meta_kubernetes_pod_container_name.log
        rule {
          action = "replace"
          replacement = "/var/log/pods/*$1/*.log"
          separator = "/"
          source_labels = ["__meta_kubernetes_pod_uid", "__meta_kubernetes_pod_container_name"]
          target_label = "__path__"
        }

        // Label creation -  "container_runtime" field from "__meta_kubernetes_pod_container_id"
        rule {
          action = "replace"
          regex = "^(\\S+):\\/\\/.+$"
          replacement = "$1"
          source_labels = ["__meta_kubernetes_pod_container_id"]
          target_label = "container_runtime"
        }
      }

      discovery.relabel "services_k8s_labels" {
          targets = discovery.kubernetes.services.targets
          rule {
              action = "labelmap"
              regex = "__meta_kubernetes_(.+)"
          }
      }

      local.file_match "node_logs" {
        path_targets = [{
            // Monitor syslog to scrape node-logs
            __path__  = "/var/log/syslog",
            cluster   = "${CLUSTER_ID}",
            job       = "node/syslog",
            node_name = sys.env("HOSTNAME"),
        }]
      }

      // loki.source.file reads log entries from files and forwards them to other loki.* components.
      // You can specify multiple loki.source.file components by giving them different labels.
      loki.source.file "node_logs" {
        forward_to = [loki.write.loki.receiver]
        targets    = local.file_match.node_logs.targets
      }

      loki.source.kubernetes "pod_logs" {
        forward_to = [loki.process.pod_logs.receiver]
        targets    = discovery.relabel.pod_logs.output
      }

      // loki.process receives log entries from other Loki components, applies one or more processing stages,
      // and forwards the results to the list of receivers in the component's arguments.
      loki.process "pod_logs" {
        stage.static_labels {
            values = {
              cluster = "${CLUSTER_ID}",
            }
        }

        forward_to = [loki.write.loki.receiver]
      }

      // loki.source.kubernetes_events tails events from the Kubernetes API and converts them
      // into log lines to forward to other Loki components.
      loki.source.kubernetes_events "cluster_events" {
        job_name   = "integrations/kubernetes/eventhandler"
        log_format = "logfmt"
        forward_to = [
          loki.process.cluster_events.receiver,
        ]
      }

      // loki.process receives log entries from other loki components, applies one or more processing stages,
      // and forwards the results to the list of receivers in the component's arguments.
      loki.process "cluster_events" {
        forward_to = [loki.write.loki.receiver]

        stage.static_labels {
          values = {
            cluster = "${CLUSTER_ID}",
          }
        }
      }

      local.file_match "logs" {
        path_targets = [
          { __path__ = "/var/log/*.log" },
        ]
      }

      loki.source.file "varlogs" {
        targets    = local.file_match.logs.targets
        forward_to = [loki.write.loki.receiver]
      }

      // Sends aggregated logs to the Loki internal ALB
      // The "X-Scope-OrgID" header identifies the tenant/organization("ums")
      loki.write "loki" {
        endpoint {
          url = "https://${LOKI_LBALANCER_URL}/loki/api/v1/push"
          headers = {
            "X-Scope-OrgID" = "ums",
          }
        }
      }

mounts:
  dockercontainers: true
  varlog: true

resources:
  limits:
    cpu: 200m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

controller:
  autoscaling:
    enabled: true
    maxReplicas: 6
    minReplicas: 2
    targetCPUUtilizationPercentage: 60
    targetMemoryUtilizationPercentage: 80

  tolerations:
    - effect: "NoExecute"
      value: "true"
      key: "CriticalAddonsOnly"

serviceAccount:
  create: true
  name: ${IRSA_NAME}
  annotations:
    eks.amazonaws.com/role-arn: ${IRSA_ARN}
  additionallabels:
    app.kubernetes.io/component: alloy
    app.kubernetes.io/instance: controller
    app.kubernetes.io/managed-by: tf-elm
    app.kubernetes.io/name: ${IRSA_NAME}
    app.kubernetes.io/part-of: monitoring
    app.kubernetes.io/stage: ${STAGE}
    app.kubernetes.io/version: ${CHART_VERSION}
