# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "aws" {
  region = "eu-central-1"
  // -- Only these AWS Account IDs may be operated on by this template
  default_tags {
    tags = {
      "Description"                  = "Placeholder"
      "Name"                         = "Placeholder"
      "DevOps:DevOps:CI/CD"          = "false/Local"
      "DevOps:DevOps:Cronjob"        = "false"
      "DevOps:DevOps:Email"          = "juho.paivarinta@DevOps.com"
      "DevOps:DevOps:LockID"         = "ums-eu-central-1-prod-tf-state-LockID"
      "DevOps:DevOps:ManagedBy"      = "OpenTofu/Terragrunt"
      "DevOps:DevOps:Region"         = "ums-eu-central-1"
      "DevOps:DevOps:Stage"          = "prod"
      "DevOps:DevOps:StateBucket"    = "ums-eu-central-1-prod-tf-state"
      "DevOps:DevOps:StateBucketKey" = "aws/eu-central-1/prod/autokrat/tf.tfstate"
      "DevOps:DevOps:Terratest"      = "false"
      "DevOps:DevOps:UpdateDatetime" = "2025-07-29T09:18:33Z"
      "DevOps:Development:Repo"      = "Placeholder"
    }
  }
}
