# Webhooks cause an unsolvable error
karpenter-crd:
  webhook:
    enabled: false

karpenter:
  enabled: true
  webhook:
    enabled: false

settings:
  clusterName: ${CLUSTER_ID}
  clusterEndpoint: ${CLUSTER_ENDPOINT}
  interruptionQueueName: ${QUEUE_NAME}

serviceAccount:
  name: ${IRSA_NAME}
  annotations:
    eks.amazonaws.com/role-arn: ${IRSA_ARN}
  labels:
    app.kubernetes.io/component: Karpenter
    app.kubernetes.io/instance: controller
    app.kubernetes.io/managed-by: helm
    app.kubernetes.io/name: ${IRSA_NAME}
    app.kubernetes.io/part-of: autoscaling
    app.kubernetes.io/stage: ${STAGE}
    app.kubernetes.io/version: ${CHART_VERSION}

controller:
  resources:
    limits:
      cpu: 2
      memory: 2Gi
    requests:
      cpu: 1
      memory: 1Gi
  livenessProbe:
    initialDelaySeconds: 1600
    timeoutSeconds: 1300
    httpGet:
      path: /healthz
      port: http
  readinessProbe:
    initialDelaySeconds: 1540
    timeoutSeconds: 1300
    httpGet:
      path: /readyz
      port: http

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: role
              operator: In
              values:
                - core

tolerations:
  - key: "CriticalAddonsOnly"
    operator: "Equal"
    value: "true"
    effect: "NoExecute"

logLevel: info
