# -- Limit iptables-based egress masquerading to interface selector
egressMasqueradeInterfaces: eth0

# -- Enables masquerading of IPv4 traffic leaving the node from endpoints
enableIPv4Masquerade: false

eni:
  enabled: true
  # -- Parameters
  awsEnablePrefixDelegation: true
  awsReleaseExcessIPs: true
  iamRole: ${irsa_arn}
  updateEC2AdapterLimitViaAPI: true

ipam:
  mode: eni

kubeProxyReplacement: true

routingMode: native

envoy:
  enabled: false

hubble:
  enabled: true

# -- Use the Wireguard because it allows node traffic encryption
encryption:
  enabled: true
  # -- Parameters
  nodeEncryption: true
  type: wireguard

# -- For some reason the k8sServiceHost cannot have the https:// as a part of the URL
k8sServiceHost: ${cluster_endpoint}

k8sServicePort: 443

tolerations:
  - effect: NoExecute
    value: "true"
    key: coreAddonsOnly
  - effect: NoSchedule
    key: node.kubernetes.io/not-ready
  - effect: NoExecute
    value: "true"
    key: node.cilium.io/agent-not-ready

operator:
  tolerations:
    - effect: NoSchedule
      key: node.kubernetes.io/not-ready
    - effect: NoExecute
      value: "true"
      key: node.cilium.io/agent-not-ready
    - effect: NoExecute
      value: "true"
      key: coreAddonsOnly
