# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
module "id_label" {
  source  = "cloudposse/label/null"
  version = "0.25.0"

  namespace   = "ums"
  environment = "ec1"
  stage       = "prod"
  name        = "audit"
  delimiter   = "-"

  label_order = ["namespace", "environment", "stage", "name"]
}
