# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "ums-eu-central-1-prod-tf-state"
    dynamodb_table = "ums-eu-central-1-prod-tf-state-LockID"
    encrypt        = true
    key            = "aws/eu-central-1/prod/audit/tf.tfstate"
    region         = "eu-central-1"
  }
}
