# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "aws" {
  region = "eu-central-1"
  # Only these AWS Account IDs may be operated on by this template
  allowed_account_ids = ["156041409035"]
  default_tags {
    tags = {
      "Description"                  = "Placeholder"
      "Name"                         = "Placeholder"
      "Unikie:DevOps:CI/CD"          = "false/Local"
      "Unikie:DevOps:Cronjob"        = "false"
      "Unikie:DevOps:Email"          = "juho.paivarinta@unikie.com"
      "Unikie:DevOps:LockID"         = "ums-eu-central-1-prod-tf-state-LockID"
      "Unikie:DevOps:ManagedBy"      = "OpenTofu/Terragrunt"
      "Unikie:DevOps:Region"         = "ums-eu-central-1"
      "Unikie:DevOps:Stage"          = "prod"
      "Unikie:DevOps:StateBucket"    = "ums-eu-central-1-prod-tf-state"
      "Unikie:DevOps:StateBucketKey" = "aws/eu-central-1/prod/core/tf.tfstate"
      "Unikie:DevOps:Terratest"      = "false"
      "Unikie:DevOps:UpdateDatetime" = "2025-10-13T09:14:21Z"
      "Unikie:Development:Repo"      = "Placeholder"
    }
  }
}
