apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ${id_label}
  labels:
    app.kubernetes.io/component: kube-prometheus-stack
    app.kubernetes.io/instance: storage
    app.kubernetes.io/managed-by: Tofu-Helm
    app.kubernetes.io/name:  ${id_label}
    app.kubernetes.io/part-of: monitoring
    app.kubernetes.io/stage: ${stage}
    app.kubernetes.io/version: ${chart_version}
provisioner: ebs.csi.aws.com
parameters:
  encrypted: "true"
  type: gp3
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
