name: DevOps Workflow

on:
  push:
    branches: ["**"]
    paths: ["src/aws/**"]

permissions:
  contents: read
  id-token: write

jobs:
  Check:
    name: Terragrunt Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check terragrunt HCL
        uses: gruntwork-io/terragrunt-action@v2
        with:
          tg_command: "hclfmt --check --diff"
          tg_dir: "src/aws/eu-north-1/prod"
          tg_version: "0.73.6"
          tofu_version: "1.9.0"

  Terragrunt:
    name: Terragrunt init
    runs-on: ubuntu-latest
    needs: ["check"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-north-1
          output-credentials: true
          role-to-assume: ${{ vars.GHA_ROLE_ARN }}

      - name: Test the AWS credentials
        run: |
          aws sts get-caller-identity

      - name: Terragrunt init
        uses: gruntwork-io/terragrunt-action@v2
        with:
          tg_command: "init"
          tg_dir: "src/aws/eu-north-1/prod"
          tg_version: "0.73.6"
          tofu_version: "1.9.0"

      - name: Terragrunt plan
        uses: gruntwork-io/terragrunt-action@v2
        with:
          tg_command: "plan"
          tg_dir: "src/aws/eu-north-1/prod"
          tg_version: "0.73.6"
          tofu_version: "1.9.0"
