name: Semantic Release

on:
  - pull_request

  # push:
  #   branches: [main]

jobs:
  semantic-release:
    name: Semantic Release
    runs-on: ubuntu-latest
    permissions:
      contents: write # Publish a GitHub release
      id-token: write # Use of OIDC for npm provenance
      issues: write # Comment on released issues
      pull-requests: write # Comment on released pull requests

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Render terraform docs and push changes back to PR
        uses: terraform-docs/gh-actions@main
        with:
          git-push: "true"
          output-file: README.md
          output-method: inject
          working-dir: src/cloud/aws

      # - name: Semantic Release
      #   uses: cycjimmy/semantic-release-action@v4
      #   with:
      #     extra_plugins: |
      #       @semantic-release/changelog
      #       @semantic-release/git
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
