name: Semantic Release

on:
  push:
    branches: [main]

jobs:
  semantic-release:
    name: Semantic Release
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          persist-credentials: true
          fetch-depth: 0

      - name: Fix Git permissions
        run: sudo chown -R $(whoami) .git

      - name: Render terraform docs and push changes back to PR
        uses: terraform-docs/gh-actions@main
        with:
          git-push: "true"
          output-file: README.md
          output-method: inject
          recursive: true
          working-dir: src/cloud/aws

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        with:
          extra_plugins: |
            @semantic-release/commit-analyzer
            @semantic-release/git
            @semantic-release/release-notes-generator
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
