serviceAccount:
  create: true
  automount: true
  name: ${irsa_name}
  annotations:
    eks.amazonaws.com/role-arn: ${irsa_arn}
  labels:
    app.kubernetes.io/component: external-secrets
    app.kubernetes.io/managed-by: tofu-helm
    app.kubernetes.io/name: ${name_label}
    app.kubernetes.io/part-of: secrets
    app.kubernetes.io/stage: ${stage}
    app.kubernetes.io/version: ${chart_version}

resources:
  limits:
    cpu: 400m
    memory: 400Mi
  requests:
    cpu: 100m
    memory: 100Mi

tolerations:
  - key: CriticalExtensionsOnly
    operator: Exists
